os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: jLuVPAB7cIfVQfISdPSRfZ0PDTAdpSk5ziqfcfpqSHvI4sczDF9V8nZiSBCIRoL42Kvy1DZHS81qQHyvhleduihfn1cjYQ80QHDFiX6lIQbb/P4b5CZpCVhGTLUYPrG1buI/nSEIrj3c4I4dgfwpv0+OUKKV1OttmE3dH0pxKqcjWpaRvPZqd/zZJsPPkVkQtuUWkdHbppjjWt2r7YuPtudjAQ5tABgexzKMHgfVCuxGdY10YUVI2pYyWtUdpyGWykYmZayyJllsG4apZhlvqDVMG8vuLnmo7NuixVLXYDXu9YFGob6+rAk5OlXep2JtCZBXLPDK3FMjrhM2EA1MQYoQHIDlI+CxcG+udyY5XJ8ETMIr/U032Oq60kIns1CTs85mddlMGsoBNbVpNMtuxzay/OSq+b+KiRP792/R5DW+fD3VsWhNMX9GY4kKUdsgaHiObbnc6784uPzHBtDFC+8cktAvYfyw2ADvO4lLQXqxvE4IO6xLVbyWxplRzs7gBLmbmQ3S8fm7shUP7b401d5sHyzfhCFn+VlHafBKuDj3qACNSZj8ueH/0mcyWzM/e2LP9yeukUSxMpQhhvOlzf64fiH0POoCfqKE1VHowMtiIvt1++CvS86G/swcSfKIxvRKc8/gVQC5eawg4jugZqPges8oX8JAIqbs5zZAEWM=
if: branch =~ /^master|release/[0-9]+\.[0-9]+$/ # Should allow PRs to these branches as well
before_install:
  - sh TestsPreprocessor.sh
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=org.molgenis:vibe
before_deploy: # Runs per provider: https://docs.travis-ci.com/user/job-lifecycle#deploying-your-code. Workaround attempt below.
  - |
    if [[ ! ${RAN_BEFORE_DEPLOY+isset} == isset ]]; then
      export RAN_BEFORE_DEPLOY=1
      # Check if travis tag is equal to version defined in pom.xml file, non-zero exit if not.
      if [[ $TRAVIS_TAG != $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) ]]; then
        exit 1
      fi
      # Generate release file.
      sh .ci/GenerateReleaseNotes.sh
    fi
deploy:
  - provider: releases
    token:
      secure: NNLoW1AQGSl3boZ7m+4anjLUUN13gXVI8M7gI4FhHRPyX9bf6zW9MZQfFUl65qJNEJucBHvtxSFyS4KnCk68P9ne1hSQrJtlOCGo8L8Yzi+Ruu+s9a+IxCJUdd4V/RUx4b9+8zxe/XGEv6UZaVBjL8LGb8eif659ONzmQL63Odtp9F8V+WBGMP2otRSQBEF6p9LgA0jMbavkd8L6nkZ28Y8bKQS0fjxlp9AYrUrz/mIDkDJscaAL6mVrZimloO1M4xDQde3ctwC9FzBlv+SjcImrUKSWyrirOL+igCAimxURyU6AGvLrXJY8eolVaEG8r9HbbMtHj6CmgVFYgU3z44nH3IyxQcfil2073RBnapyzmKUXEguLilO5jQbJUX+LSpHzKzpOk3ntimM2eiEOayO7yJzXz14xUEgVkX51G713L+EnhjasVwNsxSAbnJvDiJbOEMeXb5It6TYPl0+HmaPTWuOcrn80z4Fxw1j4qyQ3ZHkW+q6ncE/fWoO9o9QzQgOrG5fWB9xUi2AK1fn0d6EXBit28swBDs9//wrihHasjYSg/ye+GVdw8AS9Ti+ahDaK/EtcHFICfbPd73BxS/sOMVkN4scUaNHzbvpjXIEvKX2ax1dA72Er/89bC3bHuLq+LG0pY4Cu0Ss8bF1Td3vDM7//q4m4VYIJX33YVLE=
    file: "vibe-cli/target/vibe-with-dependencies-${TRAVIS_TAG}.jar"
    release_notes_file: "release_notes.md"
    name: "$TRAVIS_TAG"
    on:
      condition: $TRAVIS_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
    edge: true # opt in to dpl v2
  - provider: script
    script: mvn deploy --settings deploy/maven-settings.xml
    on:
      condition: $TRAVIS_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/