os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/build/molgenis/vibe/shared_testdata/shared"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: frPx1On3hILTKF6D+qsDeUxa3IjsIn4XVfkqus+cuQxxVCz86HZA05DbtpYPeJcE6LQmqQqZsuNlWrex7hDkzXiCBtoYGtPXdpSabpdBgztl+87UaW8MVlQS40QEIjPR3ljh9t27i44XJpM9u6pYTYiOzgMqhF9HarZoVWluLqYlVmJuAdpSw8DptZAH/uxtSjB5liy5T9CNEF2lEc0XaB0gKHcn8GaXe/XW6uqYmO5wwUp/FeRqLRadvU6N5Walo/mpnPZ0oU8sI+LhWzpi/6liLYvK7Is2fquZC3+jlw7lqLBgWxprEKv2Oshz6Vrsbwiy27Tm8P7/MwYn+MFcgcGaXqnTwN1XKXM7YhiwurXRSwsT8yXo1+v6qWOX3+ePAr+CqS0EkaZnDKsRuJwwewBR7v+5zr+t8JqPQSSj5ZQy6xjgSiu2TDqYObBH3vBL+w5gV4j/v/M1W5QYUfs3naUauUb/uvlKwiOsRcUafBbf+MxILWoFQkr+pRgEYM4NDC5fZ00NvH2dDXWGKpcaLRmePZfgNCVwbzOVomcCRQFkVjWgKGGZJFkcXWgan/UEJVtUHyNIhf3IxS0PJtXo/7rRfuzDmVSvfNSmKfkTPav0UYQMOjNaWr500QOQkVrQ2wqE3BBwm74HJZw1ojw2kV6Hq6TGG2W1zgwZlFhKAVk=
before_install:
  - bash TestsPreprocessor.sh
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=org.molgenis:vibe
deploy:
  - provider: releases
    token:
      secure: "EeoePNW8PRRvOtfqwaisLIFzPugeNM9e9+sS6zYK8Ccf11Xd9QLvzTx1H7AOoS9O35Ic7XlgQ3a4AosOIUHQCdui02ico0fAvIviWUBYGJcia3XmSykCXJZ3KcrbzN1DkZutR1bvdbXNUBHY5GU4+WMipysv3FFhmbPGtUMMyy3jC+Yqgl9E12E3i4l3OSYABosFMeFHtW5aB85cP6K6Pg0b6rlvasH3wHM45eBGKPyqL+HwZnitYnwdlHuDz5mM2cmG8VTGWk0CMZA2k+qnVX5wWkaydI/dSinFfE/RI21Vprr0+RAMTrUM1TmdsZ7NEBxZahNcr2nwjzWB7IvC1FD7oUQDQTvb8P/84XhsEy9KHoBvRSUzC3/H2gMXbtTRt8DyZkkELXMr7Lzve24u92BaIIAIH9qQR9GG7LZCGhiZP5eXww5H4aD8eEKV6ZYCWh7d0S3mcoriQftO5tGVcqbTrF208cS4Ra3Fjl4Bie/crHU9aTPt2nO2ZMW3Kjpi/9NqW91uGnF9/FngmLUf14wQoemVli9wPatUzi1eLNTe+BEMc8VJcvj5+MWsDMGlJ3ERVBrmqK2wAx2vMPWEDCj1mi0lrb4iT75A+bq2bSuSkNH2BSQjlfAuIBI1DJkNyYBaufAZvi7IKBhi4v17I9/Dd9HgQMK2s8weEXJ7/iM="
    file: "vibe-cli/target/vibe.jar"
    prerelease: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
    edge: true # opt in to dpl v2
