os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/build/molgenis/vibe/shared_testdata/shared"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: frPx1On3hILTKF6D+qsDeUxa3IjsIn4XVfkqus+cuQxxVCz86HZA05DbtpYPeJcE6LQmqQqZsuNlWrex7hDkzXiCBtoYGtPXdpSabpdBgztl+87UaW8MVlQS40QEIjPR3ljh9t27i44XJpM9u6pYTYiOzgMqhF9HarZoVWluLqYlVmJuAdpSw8DptZAH/uxtSjB5liy5T9CNEF2lEc0XaB0gKHcn8GaXe/XW6uqYmO5wwUp/FeRqLRadvU6N5Walo/mpnPZ0oU8sI+LhWzpi/6liLYvK7Is2fquZC3+jlw7lqLBgWxprEKv2Oshz6Vrsbwiy27Tm8P7/MwYn+MFcgcGaXqnTwN1XKXM7YhiwurXRSwsT8yXo1+v6qWOX3+ePAr+CqS0EkaZnDKsRuJwwewBR7v+5zr+t8JqPQSSj5ZQy6xjgSiu2TDqYObBH3vBL+w5gV4j/v/M1W5QYUfs3naUauUb/uvlKwiOsRcUafBbf+MxILWoFQkr+pRgEYM4NDC5fZ00NvH2dDXWGKpcaLRmePZfgNCVwbzOVomcCRQFkVjWgKGGZJFkcXWgan/UEJVtUHyNIhf3IxS0PJtXo/7rRfuzDmVSvfNSmKfkTPav0UYQMOjNaWr500QOQkVrQ2wqE3BBwm74HJZw1ojw2kV6Hq6TGG2W1zgwZlFhKAVk=
before_install:
  - bash TestsPreprocessor.sh
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=org.molgenis:vibe
before_deploy: # Runs per provider: https://docs.travis-ci.com/user/job-lifecycle#deploying-your-code. Workaround attempt below.
  - |
    if [[ ! ${RAN_BEFORE_DEPLOY+isset} == isset ]]; then
      export RAN_BEFORE_DEPLOY=1
      # Check if travis tag is equal to version defined in pom.xml file, non-zero exit if not.
      if [[ $TRAVIS_TAG != $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) ]]; then
        exit 1
      fi
      # Generate release file.
      sh .ci/GenerateReleaseNotes.sh
    fi
deploy:
  - provider: releases
    token:
      secure: "Sv/CNT+l08k41ny8hcVOR2lXMF+2IhslZGcY2xndFWPugkHbzXiuF6RtZc0Q1f53GzV2lUJBmnxzmKZMudjFOhypEaJADRQJxC8k3GKNpLIDbSDSRjZ0OJqCz3a4O/Q5rQNDwHfkK27HsQUwvp0XC62MG+wUMl5L5i65ptVjNtXH6v2cRzIbPRIZoIviujOiig7CZq4AGmUT+S7u4W5Ush4Quinu0jUAlltvVDf4+4A/CDO1OjuPuvfgiFcxWoxh0t9+MzpeXxn22gTSF628z4MxZT/OL82XE49KdsOuCF8ttWUj0Ettt8SdWk+ZXqNBKYQ7Zq0mrJQoHDRJ+D0TIpY1rcRFUfcTr655VRDGMgQQuA65GcYzlWwRnu3lKT3Yrk7frkQzJcg1NqXk9pNYsU8kijbun3Lt+099oA4KGvGKOiQPI5rdvRYh42rmUgG3ph/jgmN6kXNrT8NDbDUThWMwA/ZsJzTkVn6co0Fwx+cNSFonqs5/vycv8lfM4Q4eqfi0MKVWorjpWVByftVrg4dmytjepcW20un+gCh5Zu8EkoQrF/YhGx2JAcGm76zvRCL1zdABdRK9BXrbXevGoUpKGWWoNU66uA2RDArwCTYv9HzkANy1lyb/SaiT43W+42vQVsTQLDWCvi/vSJIzOsjmrPGEFQiAh5h91PlnqAw="
    file: "vibe-cli/target/vibe.jar"
    release_notes_file: "release_notes.md"
    prerelease: true
    on:
      tags: true
    edge: true # opt in to dpl v2